# Generated by Django 3.2.5 on 2021-07-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IamDB_A', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='_99popularity',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.FloatField(default=None),
        ),
    ]
